# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_historicalcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
