# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20171110_1817'),
        ('organizations', '0003_auto_20171110_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_contacts', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='HistoricalContact',
        ),
    ]
