# Generated by Django 2.0.2 on 2018-08-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_news_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='updated_on',
            new_name='date',
        ),
    ]
