# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180810_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_news', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='news',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_news', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='news',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_news', to='organizations.Organization'),
        ),
    ]
