# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='assigned_to',
            field=models.ManyToManyField(related_name='org_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizations',
            name='contact',
            field=models.CharField(max_length=200, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='subOrg',
            field=models.CharField(max_length=200, null=True, verbose_name='sub organization'),
        ),
    ]
