# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20171110_1817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_auto_20170926_1752'),
        ('organizations', '0002_auto_20171107_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('dead', 'Dead')], max_length=255, null=True, verbose_name='Status of Organization')),
                ('source', models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('existing customer', 'Existing Customer'), ('partner', 'Partner'), ('public relations', 'Public Relations'), ('compaign', 'Campaign'), ('other', 'Other')], max_length=255, null=True, verbose_name='Source of Organization')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_address', to='common.Address')),
                ('assigned_to', models.ManyToManyField(related_name='org_assigned_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='account',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
    ]
