# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20171107_1341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('startdate', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('enddate', models.DateTimeField(auto_now_add=True, verbose_name='End date')),
                ('activity_type', models.CharField(blank=True, choices=[('Email', 'Email'), ('PhoneCall', 'PhoneCall'), ('Meeting', 'Meeting')], max_length=255, null=True, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('Name', models.CharField(max_length=255, null=True, verbose_name='Activity Name')),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('dead', 'Dead')], max_length=255, null=True, verbose_name='Status of Activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_created_by', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='organizations.Organizations')),
            ],
        ),
    ]
