# Generated by Django 2.0.2 on 2018-03-23 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Activity Name')),
                ('email', models.EmailField(max_length=254)),
                ('startdate', models.DateTimeField(verbose_name='Start date')),
                ('enddate', models.DateTimeField(verbose_name='End date')),
                ('activity_type', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Call', 'Phone Call'), ('Meeting', 'Meeting')], max_length=255, null=True, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('dead', 'Dead')], max_length=255, null=True, verbose_name='Status of Activity')),
                ('assigned_to', models.ManyToManyField(related_name='activity_assigned_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
