# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Activity Name')),
                ('email', models.EmailField(max_length=254)),
                ('startdate', models.DateTimeField(verbose_name='Start date')),
                ('enddate', models.DateTimeField(verbose_name='End date')),
                ('activity_type', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Call', 'Phone Call'), ('Meeting', 'Meeting')], max_length=255, null=True, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('dead', 'Dead')], max_length=255, null=True, verbose_name='Status of Activity')),
            ],
        ),
    ]
