# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20180323_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('In Process', 'In Process'), ('Completed', 'Completed')], max_length=255, null=True, verbose_name='Status of Activity'),
        ),
    ]
