# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20171108_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='org',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Call', 'Phone Call'), ('Meeting', 'Meeting')], max_length=255, null=True, verbose_name='Activity Type'),
        ),
    ]
