# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171110_1817'),
        ('activity', '0003_auto_20171110_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activity_contact', to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
