# Generated by Django 2.0.2 on 2018-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_news_updated_on'),
        ('activity', '0003_auto_20180706_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='teams',
            field=models.ManyToManyField(to='common.Team'),
        ),
    ]
