# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171110_1817'),
        ('activity', '0004_activity_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='contact',
        ),
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
